# Generated by Django 4.2.2 on 2023-08-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(related_name='product_images', to='product.productimage'),
        ),
    ]
