# Generated by Django 4.2.2 on 2023-08-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
