# Generated by Django 4.2.2 on 2023-09-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_alter_shopcart_user_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
